name: 'Setup Environment'
description: 'Setup PHP and Composer'
runs:
  using: "composite"
  steps:
    # - name: Checkout code
    #   uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql, pdo_mysql
        coverage: xdebug
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
