name: PullRequestReview

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
    - name: Debug - Show directory and list files
      run: |
        pwd
        ls -la
    - name: Setup environment
      uses: ./.github/actions/php_setup.yaml
    - name: Run PHPUnit with testdox output
      run: ./vendor/bin/phpunit ./tests/ --testdox > phpunit.txt
    - name: Comment PHPUnit testdox result
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: phpunit.txt
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  phpsyntax:
    runs-on: ubuntu-latest
    steps:
    - name: Setup environment
      uses: ./.github/actions/php_setup.yaml
    - name: Run PHP Syntax
      run: find ./training/ -name "*.php" -exec sh -c 'php -l "$1" | grep -q "No syntax errors" || (echo "Error in $1" && php -l "$1")' _ {} \; > phpsyntax.txt
    - name: Comment PHP Syntax
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: phpsyntax.txt
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  phpstan:
    runs-on: ubuntu-latest
    steps:
    - name: Setup environment
      uses: ./.github/actions/php_setup.yaml
    - name: Run PHPStan
      run: ./vendor/bin/phpstan analyse ./training/ --level=8 --no-progress --error-format=checkstyle | reviewdog -f=checkstyle -name="PHPStan" -reporter=github-pr-review

  phpcs:
    runs-on: ubuntu-latest
    steps:
    - name: Setup environment
      uses: ./.github/actions/php_setup.yaml
    - name: Run PHP_CodeSniffer
      run: ./vendor/bin/phpcs ./training/ --report=checkstyle | reviewdog -f=checkstyle -name="PHPCS" -reporter=github-pr-review
